---
- name: install {{ service_name }}
  apt:
    name: "{{ package_apt }}"
    state: present

- name: starting and enabling {{ service_name }}
  systemd:
    name: "{{ package_apt }}"
    state: started
    enabled: yes
    masked: no

- name: colleting service facts
  service_facts:
- name: checking {{ package_apt }} status
  debug:
    var: ansible_facts.services['{{ package_apt }}.service']

- name: creating index file
  copy:
    content: "\"Welcome to my webserver\""
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache on Debian

- name: configuring ufw
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
  - "{{ port80 }}"
  - "{{ port443 }}"
  notify: Start UFW on Debian
