---
# tasks file for install_ftp

#- name: install and configure {{ service_name }} service
#  hosts: webserver
#  tasks:
- name: RedHat block
  block: 
    - name: install {{ service_name }}
      yum:
        name: "{{ package_name }}"
        state: present
      notify:
        - start ftp
    - name: configuring firewalld
      ansible.posix.firewalld:
        zone: public
        service: "{{ service_name }}"
        permanent: yes
        state: enabled
      notify:  start firewalld
  when: ansible_os_family == "RedHat"

- name: Debian block
  block:
    - name: Install {{ service_name }}
      apt:
        name: "{{ package_name }}"
      notify:
        - start ftp
    - name: configuring ufw
      community.general.ufw:
        rule: allow
        port: "{{ ftp_port }}"
        proto: tcp
      notify: start ufw
  when: ansible_os_family == "Debian"

- name: generating {{ service_name }} config
  template: src=vsftpd.j2 dest=/etc/vsftpd/vsftpd.conf
  notify: restart {{ service_name }}
