---
# tasks file for install_ftp
vars:
- anonymous_enable: YES
- local_enable: YES
- write_enable: YES
- anon_upload_enable: YES
- dirmessage_enable: YES
- listen: YES
- pam_service_name: vsftpd

- name: installing {{ package_name }}
  hosts: all
  tasks:

  - block: RHEL block
      - name: Install {{ package_name }}
        yum: name=vsftpd state=latest
      - name: Start {{ package_name }}
        systemd: name=vsftpd state=started enabled=yes
      - name: configuring firewalld
        ansible.posix.firewalld:
          port: "{{ ftp_port }}"/tcp
          permanent: yes
          state: enabled
        notify: start firewalld 
    when: ansible_os_family == "RedHat"

  - block: Debian block
      - name: Install {{ package_name }}
        apt: name=vsftpd state=latest
      - name: Start {{ package_name }}
        systemd: name=vsftpd state=started enabled=yes
      - name: configuring ufw
        community.general.ufw:
          rule: allow
          port: "{{ ftp_port }}"
          proto: tcp
        notify: start ufw
    when: ansible_os_family == "RedHat"

  - name: generating {{ package_name }} config file
